inherit_from:
  - .rubocop_todo.yml
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'Rakefile'
    - 'vendor/**/*'
  RunRailsCops: true
  DisplayCopNames: true
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 20
Style/StringLiterals:
  Enabled: false
Style/AccessModifierIndentation:
  EnforcedStyle: outdent
Style/AlignParameters:
  EnforcedStyle:
    - with_first_parameter
    - with_fixed_indentation
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
# for the following case.
#   validates :project , presence: true
#   validates :title   , presence: true
#   validates :status  , presence: true
Style/SpaceBeforeComma:
  Enabled: false
# for the following case.
#   expect(json['title']).to    eq 'implement hoge'
#   expect(json['status']).to   eq 'todo'
#   expect(json['priority']).to eq 1
#   expect(json['point']).to    eq 1
Style/SingleSpaceBeforeFirstArg:
 Enabled: false
Style/TrailingComma:
  EnforcedStyleForMultiline: comma
Style/ExtraSpacing:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
